### ISSUE TITLE
how do I get activate component to show up/hotkeyed?

### ISSUE THREAD

**Issue by dseeni** [lf-/ShortcutItPy#3]
hey I love this tool for fusion, makes hotkeying commands so much easier.. 

one issue: 
activate component does not show up? what is the proper command name to enter into the tuple? 

thanks!

**Comment by lf-** [comment]
I believe they did something to this in a recent version of Fusion and might have removed it. I haven't looked into it because I'm currently full time on SolidWorks. 

If you want to check the full command list to find it, install the script from the DumpCmdDefs folder using the instructions in the README and generate a current full command list.

**Comment by dseeni** [comment]
Found it! Thanks! Looks like they changed it to:

"FusionActivateLocalCompCmd"

**Comment by lf-** [comment]
It would be fantastic if you made a pull request to change this: to do this you can go to the file in the repository, click the pencil on the right, make the edit then submit. GitHub's documentation should have some more detailed information if you want it.
